### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by jmeile** [SysLord/YamahaEL90B00Parser#1]
Hi

Since I don't see any email address from  you, I'm using this to contact you.

Would be possible to include some build-in instructions? I saw that your project requires the java SE Development kit and Apache Maven. I tried to build your project, so, I install java and downloaded Maven. Then I setup them in the environment variables as follows:

`Path=...<some_paths_come_here>...;c:\Program Files\Java\jdk1.8.0_201\bin:C:\Users\my_user\Desktop\Electone Parser\apache-maven-3.6.0\bin;`

`JAVA_HOME=C:\Program Files\Java\jdk1.8.0_201`

If I open a command prompt and give:
`javac`
`mvn -h`

Both commands are working. So, know I went to the place where I stored your project
`cd \Users\jmeile\Desktop\Electone Parser\YamahaEL90B00Parser-master`

then I compiled it with Maven:
mvn package

It builds without any problem. Then I tried to run it:
`java -cp target\el90b00parser-0.0.1-SNAPSHOT.jar parser.main.Main`

But then I see:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
        at parser.util.LogUtil.<clinit>(LogUtil.java:9)
        at parser.main.Main.main(Main.java:23)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```

I know that you need to give a B00 file as a parameter, but the software should log this and not generate an exception. Clearly, the class "org/apache/logging/log4j/LogManager" isn't found. What else is required and how should you add it?

I'm working in a similar project with an Electone HS. So, that's why I want to see how your project works. Perhaps it helps me to understand the format of user patterns for my organ.

Thanks
Josef

**Comment by jmeile** [comment]
Ok, now I even passed a .B00 file and I got:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at parser.main.Main.toIntbasedBinaryData(Main.java:49)
        at parser.main.Main.main(Main.java:29)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```

So, there are other things needed here

**Comment by jmeile** [comment]
I tried this commands:
```
mvn compile
mvn test
mvn package
```

All they work. The question is what do you use to run it? I tried this:
`java -cp target\el90b00parser-0.0.1-SNAPSHOT.jar parser.main.Main RHY_MDR_00.B00`

But it is giving the problems I already mentioned before.

**Comment by SysLord** [comment]
Hi, just found your notifications in my emails. I'm very sorry I didn't see it sooner.
I will take a look at this old project on the weekend. This is from my not-so-professional software development days, so the documentation sucks obviously.
I would be interested from musical standpoint what you are implementing.

It seems this project contains the newer version of the B00 Parser and visual pattern editor: https://github.com/SysLord/YamahaEl90PatternEditor

**Comment by jmeile** [comment]
Thanks for your answer.

Actually, I also don't have many time, so, my project is now on stand-by. My idea is to create a python script that takes SysEx dumps from my organ: HS-8, then translate them to a human readable format. Here the possible dumps I want to process:

1. Full RAM dump (All other dumps on the same SysEx)
2. Registration
3. Chord and Rhythm Sequences (CSP and RSP)
4. Full Music Performance (FMP)
5. User pattern
6. User voice

I already implemented point 3. (CSP and RSP). The others are still missing. I already had the specification of the points: 1., 2., 3., 4., and 6..

I have to confess that my real motivation is point 5., the user patterns (or also known as user styles). But as you see, I don't have the specification of this. So, I'm trying to reverse engineering it as you did with the B00 format. The main utility of this would be to be able to convert those styles to another keyboards.

I will take a look at the other project.

Thanks
Josef
